### ISSUE TITLE
How to create a Watson Studio project via NLC

### ISSUE THREAD

**Issue by naterry** [ibm-cloud-docs/natural-language-classifier#89]
After provisioning a NLC instance in an IBM Cloud Account which I am a member of, using the Launch Watson Studio button generates the following error '"Unexpected error fetching role or asset"' when attempting to create the NLC project,

Root Cause:

The user does not permission to create a project within Watson Studio in the given account.

Solutions:

1) Enable storage delegation within Watson Studio as per https://dataplatform.cloud.ibm.com/docs/content/wsj/getting-started/setup-addl-users.html

2) Have the IBM Cloud Account owner launch NLC and create the project, and invite the user to it.

-----

Can the documentation for NLC be improved to notify users of this who are members of a given IBM Cloud Account?

**Comment by SirSpidey** [comment]
@naterry Thanks for reporting. I'm taking this to the dev team to understand what happened.

**Comment by SirSpidey** [comment]
@naterry Following up on this. The Watson Studio team now has the issue to handle this error.
